/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MermaidImport } from './routes/mermaid'
import { Route as ExcalidrawImport } from './routes/excalidraw'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MermaidRoute = MermaidImport.update({
  id: '/mermaid',
  path: '/mermaid',
  getParentRoute: () => rootRoute,
} as any)

const ExcalidrawRoute = ExcalidrawImport.update({
  id: '/excalidraw',
  path: '/excalidraw',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/excalidraw': {
      id: '/excalidraw'
      path: '/excalidraw'
      fullPath: '/excalidraw'
      preLoaderRoute: typeof ExcalidrawImport
      parentRoute: typeof rootRoute
    }
    '/mermaid': {
      id: '/mermaid'
      path: '/mermaid'
      fullPath: '/mermaid'
      preLoaderRoute: typeof MermaidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/excalidraw': typeof ExcalidrawRoute
  '/mermaid': typeof MermaidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/excalidraw': typeof ExcalidrawRoute
  '/mermaid': typeof MermaidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/excalidraw': typeof ExcalidrawRoute
  '/mermaid': typeof MermaidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/excalidraw' | '/mermaid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/excalidraw' | '/mermaid'
  id: '__root__' | '/' | '/excalidraw' | '/mermaid'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExcalidrawRoute: typeof ExcalidrawRoute
  MermaidRoute: typeof MermaidRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExcalidrawRoute: ExcalidrawRoute,
  MermaidRoute: MermaidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/excalidraw",
        "/mermaid"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/excalidraw": {
      "filePath": "excalidraw.tsx"
    },
    "/mermaid": {
      "filePath": "mermaid.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
