/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MermaidImport } from './routes/mermaid'
import { Route as DrawImport } from './routes/draw'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MermaidRoute = MermaidImport.update({
  id: '/mermaid',
  path: '/mermaid',
  getParentRoute: () => rootRoute,
} as any)

const DrawRoute = DrawImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawImport
      parentRoute: typeof rootRoute
    }
    '/mermaid': {
      id: '/mermaid'
      path: '/mermaid'
      fullPath: '/mermaid'
      preLoaderRoute: typeof MermaidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draw': typeof DrawRoute
  '/mermaid': typeof MermaidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draw': typeof DrawRoute
  '/mermaid': typeof MermaidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/draw': typeof DrawRoute
  '/mermaid': typeof MermaidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/draw' | '/mermaid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/draw' | '/mermaid'
  id: '__root__' | '/' | '/draw' | '/mermaid'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrawRoute: typeof DrawRoute
  MermaidRoute: typeof MermaidRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrawRoute: DrawRoute,
  MermaidRoute: MermaidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/draw",
        "/mermaid"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/draw": {
      "filePath": "draw.tsx"
    },
    "/mermaid": {
      "filePath": "mermaid.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
